!!
!! 1. INCLUDE FILE DATA: File names.
!!
      MODULE include_file_                                              
                                                                        
      TYPE :: include_file_type                                         
        INTEGER          File_Number     ! Included input file number.     
        INTEGER          Line_Number     ! Position in input file.         
        INTEGER          LAYUP_Begin     ! Position of 1st  LAYUP record.  
        INTEGER          LAYUP_End       ! Position of last LAYUP record.  
        INTEGER          LSOLD_Begin     ! Position of 1st  LSOLD record.  
        INTEGER          LSOLD_End       ! Position of last LSOLD record.  
        INTEGER          CONTROL_Begin   ! Position of 1st  CONTROL record.
        INTEGER          CONTROL_End     ! Position of last CONTROL record.
        CHARACTER(1024)  Full_Name       ! File name generated by INQUIRE. 
      END TYPE                                                          
                                                                        
      TYPE (include_file_type), &
     & DIMENSION(:), ALLOCATABLE :: INCLUDE_FILE                                                                 
                                                                        
      END MODULE include_file_
